### ISSUE TITLE
Adaptar todas as telas de Clientes para atender as informações de tipos de cliente

### ISSUE THREAD

**Issue by sigespweb22** [sigespweb22/boxapp-front#28]
Todas as telas onde for necessário deverá permitir ao usuário informar qual o tipo de pessoa é o cliente (Pessoa Física ou Pessoa Jurídica)

**Comment by D41K1** [comment]
Opção: PJ ou PF

PJ: 
  id: string
  nomeFantasia: string
  razaoSocial: string
  inscricaoEstadual: string
  cnpj: string
  telefonePrincipal: string
  emailPrincipal: string
  observacao: string
  dataFundacao: string
  codigoMunicipio: number
  rua: string
  numero: string
  complemento: string
  cidade: string
  estado: string
  cep: string
  status: string

 PF: 
  id: string
  nome: string
  cpf: string
  telefonePrincipal: string
  emailPrincipal: string
  observacao: string
  codigoMunicipio: number
  rua: string
  numero: string
  complemento: string
  cidade: string
  estado: string
  cep: string
  status: string
