### ISSUE TITLE
Check ACL em toda aplicação

### ISSUE THREAD

**Issue by sigespweb22** [sigespweb22/boxapp-front#40]

**Comment by sigespweb22** [comment]
Vamos mapear todas as telas do sistema, e efetuar testes de controle de acesso em tudo quanto for necessário.

Iremos criar um usuário teste, vinculá-lo a um grupo com permissões que iremos adicionando pouco a pouco, conforme a evolução dos teste

**Comment by sigespweb22** [comment]
- [ ] dfasd
- [ ] asdfasd
- [ ] asdf

**Comment by D41K1** [comment]
•	Perfil só consegue ser acessado com a role master
•	Read e update em clientes não consegue ser acessado mesmo com as suas respectivas roles junto com a de clientesContratosList
•	Ao tentar mudar o status de um cliente com as roles ClienteUpdate e ClienteDelete aparece o erro de não ter permissão

**Comment by sigespweb22** [comment]
@D41K1 , finalizei os ajustes, sendo assim, pode voltar a efetuar os testes.
Amanhã me procure que vou te explicar alguns detalhes  e te orientar melhor quanto a sequência destes testes.

**Comment by D41K1** [comment]
Read e update em clientes consegue ser acessado com as suas respectivas roles junto com a de clientesContratosList

Perfil agora precisa ter a role user read para poder acessar a página e user update para atualizar as informações nela
