### ISSUE TITLE
Problemas ao acessar tela perfil de usuário

### ISSUE THREAD

**Issue by sigespweb22** [sigespweb22/boxapp-front#42]
Acesso não autorizado, quando o usuário possui a role de acesso

**Comment by sigespweb22** [comment]
Irei implementar as claims como uma camada para gerir as ações e subjects das permissões.
Será implementado tudo na versão 1.7.0

**Comment by D41K1** [comment]
Para acessar a página de usuário, é preciso ter a role user read e para atualizar qualquer informação nela é preciso ter a role user update
