### ISSUE TITLE
Bug na visualização de erro ao criar um usuário duplicado

### ISSUE THREAD

**Issue by D41K1** [sigespweb22/boxapp-front#69]
Ao tentar criar um usuário com um email já cadastrado no sistema o sistema aparece com a mensagem usuário criado com sucesso mesmo não sendo criado.

**Comment by sigespweb22** [comment]
Implementado verificação de sucesso ao criar novo usuário via new IdentityResult(), sendo assim, recupero o erro em caso de alguma inconsistência na criação e retorno para o front
