### ISSUE TITLE
UI faltando na table left

### ISSUE THREAD

**Issue by D41K1** [sigespweb22/boxapp-front#78]
UI diferente da role master para as outras na tableLeft

![Image](https://user-images.githubusercontent.com/72043758/205943877-fd13a020-4de0-48b3-a6f1-9564cf5a3f68.png)

![Image](https://user-images.githubusercontent.com/72043758/205943990-6598b9b9-e657-4820-90da-601435e80263.png)

**Comment by sigespweb22** [comment]
Já identifiquei o problema.
Deverá ser atribuído a esta área de navegação do menu um subject e uma action, ao qual o usuário deverá possui para consegui visualizar esta área do menu.

Será implementado depois de solucionar a estrutura cd acl com as claims. Assim será possível testar com mais precisão.
